import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


public class Transection extends javax.swing.JFrame {
Connection con=null;
 PreparedStatement pst=null;
 ResultSet rs=null;
 int Total=0;
 int Item_Total_price=0;
    
    public Transection() {
        initComponents();
        con = DB_connect.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pr1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        T2 = new javax.swing.JTextField();
        T3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ad1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        pr1.setText("Print");
        pr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pr1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Paws Shop");
        getContentPane().setLayout(null);

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Unit_Price", "Quantity", "Price"
            }
        ));
        jScrollPane1.setViewportView(Table1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(1, -6, 290, 310);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Product ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(308, 39, 100, 25);

        T1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T1ActionPerformed(evt);
            }
        });
        getContentPane().add(T1);
        T1.setBounds(410, 43, 113, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Quantity:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(308, 77, 90, 25);

        T2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T2ActionPerformed(evt);
            }
        });
        getContentPane().add(T2);
        T2.setBounds(410, 81, 113, 22);
        getContentPane().add(T3);
        T3.setBounds(400, 168, 123, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Total:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(308, 168, 60, 25);

        ad1.setText("Add");
        ad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad1ActionPerformed(evt);
            }
        });
        getContentPane().add(ad1);
        ad1.setBounds(450, 240, 72, 23);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(450, 270, 72, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\SVMyCtb.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(287, 0, 250, 300);

        setSize(new java.awt.Dimension(543, 334));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void T2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T2ActionPerformed

    private void ad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad1ActionPerformed
       String text = T1.getText();
       String tex = T2.getText();
      int tex_C = Integer.parseInt(tex.trim());
         System.out.println("ID:"+text+" Quantity :"+tex_C );
        int To=0;  
         try{
             String sql1="SELECT Unit_Price,Quantity FROM add_items Where ID=?";
             pst=con.prepareStatement(sql1);
             pst.setString(1,text);
             rs=pst.executeQuery();
             System.out.println("SQl Connection done:");
             if(rs.next()){//Retrive data from Database               
                int P_Price=rs.getInt("Unit_Price");
                int P_Qty = rs.getInt("Quantity");
                System.out.println("Data Reading done:    Price"+P_Price+"   Quantity="+P_Qty);
         
                if(P_Qty>=tex_C){
                    int Item_Total_price = tex_C*P_Price;
                    To = To+Item_Total_price;
               System.out.println("Item Total:"+Item_Total_price+"  Total :"+To);
               String Tot=String.valueOf(To);
                    String Req_Qty = null;
               String DataROw[]={text,String.valueOf(P_Price),tex,String.valueOf(Item_Total_price)};
               
               DefaultTableModel tbModel=(DefaultTableModel)Table1.getModel();
                 tbModel.addRow(DataROw);
                 T3.setText(Tot);
                 T1.setText("");
                 T2.setText("");
                 P_Qty=P_Qty-tex_C;
                 try{
                     System.out.print("Update Starting !");
                     String Sql2="UPDATE product SET Quantity=? Where ID=?";
                     pst=con.prepareStatement(Sql2);
                     pst.setInt(1,P_Qty); 
                     pst.setString(2,text);
                     int rowsAffected=pst.executeUpdate();
                     if(rowsAffected>0){
                         System.out.print("Update Done !");
                     }
                }
                 catch( SQLException Ex){
                     
                 }
               
                }
                else{
                 JOptionPane.showMessageDialog(null, "Sorry.We don't have enough Stocks at this moment", "Stock Inquary", JOptionPane.ERROR_MESSAGE);
             }
             }
         }
         catch(SQLException e){
            System.out.println("Sql Exception"+e);
            
        }
                
    }//GEN-LAST:event_ad1ActionPerformed

    private void pr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pr1ActionPerformed

       
    }//GEN-LAST:event_pr1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void T1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTable Table1;
    private javax.swing.JButton ad1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pr1;
    // End of variables declaration//GEN-END:variables
}
